#!/usr/bin/python3
import os

def run():
    for i in os.listdir(sys.argv[1]):
        os.system(f"gmi2html --inline-all < {sys.argv[1]+i} > {i.split('.')[0]+'.html'}")
        os.system(f"sup {i.split('.')[0]+'.html'}")
    os.system("rm -rf *.html")

if __name__ == "__main__":
    run()

    
